config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :user_groups
  resources :users
  devise_for :users
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < User
end

app/models/post.rb
class Post < ApplicationRecord
  has_and_belongs_to_many :user_groups

  has_attached_file :picture, styles: { medium: '300x300>', thumb: '150x150>' }, default_url: '/images/:style/missing.png'
  has_attached_file :attached_file

  validates_attachment :picture, content_type: { content_type: 'image/jpeg' }, size: { in: 0..5.megabytes }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  has_and_belongs_to_many :user_groups

  def admin?
    is_a? Admin
  end

  def employee?
    is_a? Employee
  end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_and_belongs_to_many :users
  has_and_belongs_to_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def pagination_params
    {
      page:     params[:page],
      per_page: 5
    }
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  decorates_assigned :post

  def index
    @posts = Post.all.paginate(pagination_params)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    render :new unless @post.save

    redirect_to @post, notice: t('notices.created', item: Post.name)
  end

  def update
    render :edit unless @post.update(post_params)

    redirect_to @post, notice: t('notices.updated', item: Post.name)
  end

  def destroy
    @post.destroy

    redirect_to posts_url, notice: t('notices.destroyed', item: Post.name)
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(
      :title,
      :content,
      :picture,
      :attached_file,
      user_group_ids: []
    )
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :set_user_group,        only: %i[show edit update destroy]
  before_action :create_new_user_group, only: %i[index]

  def index
    @user_groups = UserGroup.all
  end

  def create
    @user_group = UserGroup.new(user_group_params)

    render :new and return unless @user_group.save

    redirect_to @user_group, notice: t('notices.created', item: UserGroup.name)
  end

  def update
    render :edit unless @user_group.update(user_group_params)

    redirect_to @user_group, notice: t('notices.updated', item: UserGroup.name)
  end

  def destroy
    @user_group.destroy

    redirect_to user_groups_url, notice: t('notices.destroyed', item: UserGroup.name)
  end

  private

  def set_user_group
    @user_group = UserGroup.find(params[:id])
  end

  def create_new_user_group
    @user_group = UserGroup.new
  end

  def user_group_params
    params.require(:user_group).permit(
      :name,
      post_ids: [],
      user_ids: []
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user,        only: %i[edit update destroy]
  before_action :create_new_user, only: %i[index new]

  def index
    @users = User.all.paginate(pagination_params)
  end

  def create
    @user = User.new(user_params)

    render :new and return unless @user.save

    redirect_to users_path, notice: t('notices.created', item: User.name)
  end

  def update
    redirect_to users_path and return if @user.update(user_params)

    redirect_to edit_user_path(@user), notice: t('notices.updated', User.name)
  end

  def destroy
    @user.destroy

    redirect_to users_path, notice: t('notices.destroyed', item: User.name)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def create_new_user
    @user = User.new
  end

  def user_params
    params.require(:user).permit(
      :email,
      :first_name,
      :last_name,
      :password,
      :password_confirmation,
      user_group_ids: []
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def humanize_attribute(attribute)
    attribute.to_s.humanize
  end

  def form_group(attribute, form, field_type)
    content_tag(:div, class: 'form-group') do
      form.label(attribute) +
          form.send(field_type, attribute, class: 'form-control')
    end
  end

  def flash_class(level)
    case level.to_sym
    when :notice  then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error   then 'alert alert-error'
    when :alert   then 'alert alert-error'
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title HRDepartment
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = render 'shared/navbar'
    .container-fluid
      = render 'shared/notices'
      = yield

app/views/posts/_form.html.haml
= form_for @post do |f|
  = render 'shared/form_errors', item: @post

  = form_group(:title,         f, :text_field)
  = form_group(:content,       f, :text_area)
  = form_group(:picture,       f, :file_field)
  = form_group(:attached_file, f, :file_field)

  .actions= f.submit t('defaults.save'), class: 'form-control'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
.container
  .well
    .media
      .pull-left
        = image_tag post.picture.url(:thumb)
      .media-body
        %h4.text-left= post.title
        %p.pull-right= post.created_ago
        %p= post.content

app/views/shared/_collapsed.html.haml
.panel-group
  .panel.panel-default
    .panel-heading
      .panel-title
        %a{ href: "##{id}", data: { toggle: 'collapse' }}= title
    .panel-collapse.collapse{ id: id }
      .panel-body
        = yield

app/views/shared/_form_errors.html.haml
- if item.errors.any?
  #error_explanation
    %ul
      - item.errors.full_messages.each do |message|
        %li= message

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      %a.navbar-brand= I18n.t('defaults.title')
    %ul.nav.navbar-nav
      %li.active
        = link_to t('navbar.users'), users_path
      %li
        = link_to t('navbar.user_groups'), user_groups_path
      %li
        = link_to t('navbar.posts'), posts_path

app/views/shared/_notices.html.haml
- flash.each do |key, value|
  %div{ class: flash_class(key) }= value

app/views/user_groups/_form.html.haml
= form_for @user_group do |f|
  = render 'shared/form_errors', item: @user_group

  = form_group(:name, f, :text_field)
  = collection_select(:user_group, :author_id, Author.all, :id, :name_with_initial, {:selected => current_book.authors.map(&:id)})


  .actions= f.submit t('defaults.save'), class: 'form-control'

app/views/user_groups/edit.html.haml
= render 'form'

app/views/user_groups/index.html.haml
%h1 Listing user_groups

%table
  %thead
    %tr
      %th
      %th
      %th

  %tbody
    - @user_groups.each do |user_group|
      %tr
        %td= link_to 'Show', user_group
        %td= link_to 'Edit', edit_user_group_path(user_group)
        %td= link_to 'Destroy', user_group, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New User group', new_user_group_path

app/views/user_groups/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_user_group_path(@user_group)
\|
= link_to 'Back', user_groups_path

app/views/users/_form.html.haml
= form_for @user, as: :user, url: users_path do |f|
  = render 'shared/form_errors', item: @user

  = form_group(:email,      f, :email_field)
  = form_group(:first_name, f, :text_field)
  = form_group(:last_name,  f, :text_field)

  = form_group(:password,              f, :password_field)
  = form_group(:password_confirmation, f, :password_field)

  .actions= f.submit t('defaults.save'), class: 'form-control'

app/views/users/_user_groups.html.haml
= form_for @user, as: :user, url: user_path(@user) do |f|
  = f.collection_check_boxes(:user_group_ids, UserGroup.all, :id, :name) do |b|
    .my-checkbox-wrapper
      = b.label do
        = b.check_box
        = b.text

  .actions= f.submit t('defaults.save'), class: 'form-control'

app/views/users/edit.html.haml
%h1 Editing user

.container
  %ul.nav.nav-tabs
    %li.active
      %a{ data: { toggle: 'tab' }, href: '#user-form' }= t('defaults.edit')
    %li
      %a{ data: { toggle: 'tab' }, href: '#user-groups'}= t('users.user_groups')

  .tab-content
    #user-form.tab-pane.fade.in.active
      = render 'form'
    #user-groups.tab-pane.fade
      = render 'user_groups'

app/views/users/index.html.haml
= render('shared/collapsed', id: 'create-container', title: t('users.create')) { render 'form'}

%table.table.table-responsive.table-striped
  %thead
    %th= humanize_attribute(:email)
    %th= humanize_attribute(:first_name)
    %th= humanize_attribute(:last_name)
    %th

  %tbody
    - @users.each do |user|
      %tr
        %td= user.email
        %td= user.first_name
        %td= user.last_name
        %td
          = link_to t('defaults.destroy'), user_path(user), method: :delete, data: { confirm: t('defaults.confirmation') }, class: 'btn btn-danger pull-right'
          = link_to t('defaults.edit'), edit_user_path(user), class: 'btn btn-primary pull-right'

= will_paginate @users, renderer: WillPaginate::ActionView::Bootstrap4LinkRenderer

app/views/users/new.html.haml
%h2= t('users.create')

= render 'form'